FROM openjdk:17-jdk-alpine

COPY build/libs/hazina-0.0.1-SNAPSHOT.jar hazina.jar

ENTRYPOINT ["java","-jar","/hazina.jar"]



#VOLUME /tmp
#ARG JAR_FILE
#COPY ${JAR_FILE} hazina.jar
#ENTRYPOINT ["java","-jar","/hazina.jar"]

